# Generated by Django 3.2.6 on 2021-08-29 01:48

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_espec', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_espec', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula_cli', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_cli', models.CharField(max_length=64)),
                ('apellido_cli', models.CharField(max_length=64)),
                ('direccion_cli', models.CharField(max_length=64)),
                ('correo_cli', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('cedula_doc', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_doc', models.CharField(max_length=64)),
                ('apellido_doc', models.CharField(max_length=64)),
                ('direccion_doc', models.CharField(max_length=64)),
                ('correo_doc', models.CharField(max_length=80)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='gestion.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historia', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('historia', models.TextField(max_length=builtins.max)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_pacientes', to='gestion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_pacientes', to='gestion.paciente')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosultas_medicos', to='gestion.medico')),
            ],
        ),
    ]
