# Generated by Django 3.2.6 on 2021-09-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_historial_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='id_espec',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Código Especialidad'),
        ),
    ]
